logging:
  level: 
    tmelo.recipeproject: debug
    
spring:
  datasource:
    url: jdbc:mysql://dockerserver-lb-485393680.us-east-1.elb.amazonaws.com:3306/sfg_dev
    username: root
    password: mysqladmin1
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql